# Generated by Django 5.0.3 on 2026-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_job_options_alter_jobmatch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmatch',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='matched_skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='missing_skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='recommendations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
